### PR TITLE
iOS 11, Swift 4 and iPhone X support

### PR DESCRIPTION
**Pull request by johnnyoin**

### CODE REVIEW

**Comment by ra1028** [comment]
Thanks @johnnyoin !
Could you fix merge conflicts caused by this PR?
https://github.com/ra1028/FloatingActionSheetController/pull/6

**Comment by johnnyoin** [comment]
It's done 😉

**Comment by ra1028** [comment]
Thanks @johnnyoin

**Comment by ra1028** [comment]
FloatingActionSheetController 2.1.0 is out!
https://cocoapods.org/pods/FloatingActionSheetController

**Pull request merged**
