### PR TITLE
Access level changed to fileprivate

### LINKED ISSUE #5: Compile error in Swift 3.0.2
I got this compile error:
overriding var must be as accessible as its enclosing type

The problem is related to the property **isHighlighted** of the class **ActionButton**: it can't be less visible than the superclass.

Please fix it,
Thank you

### PR DESCRIPTION
**Pull request by staticdreams**
Fixes #5

### CODE REVIEW

**Comment by cnbuff410** [comment]
Can we have this fix merged?

**Comment by cnbuff410** [comment]
Bump

**Comment by z-br** [comment]
Please merge this!

**Comment by ra1028** [comment]
Sorry, I'm delay to merge🙏 
Thanks!

**Pull request merged**
